### ISSUE TITLE
Sizing naming conventions

### ISSUE THREAD

**Issue by castastrophe** [castastrophe/wc-theming-standards#3]
Is `alpha` the larger or `zeta` the larger typography element?  Or should we go with a different naming convention all together?

**Comment by michael-collins** [comment]
For me, alpha being larger seems more intuitive. Are alpha and beta going to used as modifiers? A modifier to a `thing` like, `thing-alpha` means that it's now larger than the original `thing` and `thing-beta` is a smaller version. Perhaps they could be chained like `thing-alpha-alpha` is 2increments/units larger, and `thing-beta-beta` is two increments smaller. Maybe this adds complexity instead of being useful to how you envisioned using the convention?

**Comment by castastrophe** [comment]
I think stacking would add complexity.  The proposal I'm putting forward is the use of `--alpha` as loose map to an h1 for example but without tying it specifically to a specific html tag.

So creating a language around heading levels:
```
1 - alpha - 32px
2 - beta - 30px
3 - gamma - 28px
```

These levels would be used for font-size, font-weight, and line-height because you could create a design layer for example wherein the font-size for alpha and beta are the same but maybe weight is heavier on alpha with a larger line-height and that is what creates the hierarchy.

**Comment by michael-collins** [comment]
Gotcha. How many of these do you anticipate needing?

**Comment by castastrophe** [comment]
Typically about 6 (roughly h1-h6) - honestly, most pages I engage with don't have h-levels below h4 but the sizing is abstracted because an h2 in one context might be mapped to the `beta` level while in another component's context that same level could be mapped to `gamma` or smaller.

The typography section on the wiki lists out all the proposed names for the typography levels.

**Comment by btopro** [comment]
Would there be a way of incorporating responsive typography into this or a way of mixing two naming conventions together? Alpha and beta might look completely dissimilar on a desktop but almost identical when on mobile for example. other design setups have a breakpoint as name + size thing so just curious if that'd factor in some how or if there's a different modifier needed.

**Comment by castastrophe** [comment]
@btopro great point!  I envision the web component itself being opinionated about this.  So if I want to adjust sizing based on element queries or media queries, it could look something like this:

```css
:host {
    --local--FontSize: var(--theme--FontSize--beta, 30px);
}

::slotted(h1) {
    font-size: var(--local--FontSize);
    @media screen and (min-width: 992px) {
        --local--FontSize: var(--theme--FontSize--alpha, 32px);
    }
}
```

or using ems:

```css
:host {
    font-size: var(--theme--FontSize--alpha, 32px);
}

::slotted(h1) {
    font-size: 1em;
    @media screen and (min-width: 992px) {
        font-size: 1.1em;
    }
}
```
