### ISSUE TITLE
shadow vs global cascade in both naming and implementation of fallback vars

### ISSUE THREAD

**Issue by btopro** [castastrophe/wc-theming-standards#4]
I dono how to frame the idea, but is there maybe a way we could have like a global scope name space to a variable and then a logical locally scoped override, to avoid things like this:

```
- global
  - e-l1
    - e-l2
      - e-l3
```

global css var : `:root { --wc-theme-font-size: 10em; }`
e-l2: 
```css
:host { 
  --wc-theme-font-size: 4em;
  font-size: var(--wc-theme-font-size);
}
e-l3 {
  --wc-theme-font-size: 8em;
}
```
e-l3: `:host { font-size: var(--wc-theme-font-size);`

It's now confusing when in e-l3 as to why it picked up 8 and not 4 (if new to Shadow in general)  and traditional CSS as to why not 10.

## thinking as I type
It feels like maybe there's something that could be done similar to how PFE had those prefix named slots to ensure it was logical to look at as far as what element slotted to who's shadow dom, but with naming in variables and the implementation convention.
global css var : `:root { --wc-theme-font-size: 10em; }`
e-l1: `e-l2 { --wc-theme-font-size-override: 4em;}`
e-l2:
```css
:host { 
  font-size: var(--wc-theme-font-size-override, --wc-theme-font-size);
}
e-l3 { 
  --wc-theme-font-size-override: 8em;
}
```
e-l3: `:host { font-size: var(--wc-theme-font-size-override, --wc-theme-font-size);`

Not saying *exactly the above* but something that would be a variation to say "in this instance I am highjacking this globally available, cascading variable, but it is still effectively a locally scoped variation of the global".

**Comment by castastrophe** [comment]
I think the key here is that we should not override theme variables inside web components.  Web components are checking to see if a theme exists and then defining fallbacks for if they don't but we don't want to intercede with the value of the theme.

On your page:
```css
:root {
  --wc-theme--FontSize: 4em;
}
```

In the web component:
```css
// Opting into theme with a fallback value
:host { 
  --local--FontSize: var(--wc-theme--FontSize, 3em);
  font-size: var(--local--FontSize);
}

// But allow the component to ignore theme entirely if you want
e-l3 {
  --local--FontSize: 8em;
}
```
